<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>TO UPDATE BASIC/PERSONAL/ACCOUNT/ACADEMIC INFORMATION</description>
   <name>update_profile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-13T14:37:25</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>501414c7-4f9e-4cfd-81ef-3a9987762d88</testSuiteGuid>
   <testCaseLink>
      <guid>d25dcdf8-bead-44bc-9a89-9aec581e0faf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Page</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ab2dfcd0-efdd-4cd7-9a9b-14561168465b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Profile</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>88312592-7792-46ef-9ea7-8a558c14a335</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/basic_info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec2ef1e7-58e7-49ec-adb2-d1ef2e10f105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>725bcfc7-dbfc-4c61-a3c0-c00b5eceb021</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51352043-6e1a-4192-94b1-117958022928</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f886ea72-3384-43af-8e78-f3046950a4ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2955a0aa-ad75-4e65-83a1-76a0cfc79254</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5493261b-eb5c-48a0-a143-ab1bc008bfa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa714c9b-ea60-4b7f-8180-da917369f401</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d500081f-e0ab-49e3-83fd-bd76fb3d600d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Academic_info</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>460e11dd-eacd-4fcd-8f6d-d03385774cba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Personal_info</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f72ea825-4855-4c8a-afd4-d5bb6e7349b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/account_info</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
