<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>update_basic_info</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-11-13T11:43:57</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ed072b24-a2a4-4e9d-858e-9b30c75cd9d2</testSuiteGuid>
   <testCaseLink>
      <guid>4c38ca6e-2c49-4870-b1b7-b842893123cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login Page</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7355c187-be9b-410b-9f07-63bb3a5b69ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Profile</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4c0475be-fc89-4d84-9cd0-54eb129d00a9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/basic_info</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec2ef1e7-58e7-49ec-adb2-d1ef2e10f105</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>725bcfc7-dbfc-4c61-a3c0-c00b5eceb021</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51352043-6e1a-4192-94b1-117958022928</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f886ea72-3384-43af-8e78-f3046950a4ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2955a0aa-ad75-4e65-83a1-76a0cfc79254</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5493261b-eb5c-48a0-a143-ab1bc008bfa8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa714c9b-ea60-4b7f-8180-da917369f401</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
